// Code generated by mockery v2.46.0. DO NOT EDIT.

package repomocks

import mock "github.com/stretchr/testify/mock"

// OtelPkgInterface is an autogenerated mock type for the OtelPkgInterface type
type OtelPkgInterface struct {
	mock.Mock
}

// NewOtelPkgInterface creates a new instance of OtelPkgInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOtelPkgInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OtelPkgInterface {
	mock := &OtelPkgInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
